
# Spring boot server port set
server:
  port: 9090
  forward-headers-strategy: framework

# MySQL 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # DB Source URL
    url: jdbc:mysql://localhost:3306/sanneomeo?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    # DB username
    username: ssafy
    # DB password
    password: ssafy
  # true 설정시 JPA 쿼리문 확인 가능
  jpa:
    show-sql: true
    # DDL(create, alter, drop) 정의시 DB의 고유 기능을 사용할 수 있다.
    hibernate:
      ddl-auto: update
    # JPA의 구현체인 Hibernate가 동작하면서 발생한 SQL의 가독성을 높여준다.
    properties:
      hibernate.format_sql: true